# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser_task.proto\x12\x12user_task_protocol\"\\\n\x17\x43ompleteUserTaskRequest\x12\x15\n\ruser_task_key\x18\x01 \x01(\x03\x12\x11\n\tvariables\x18\x02 \x01(\t\x12\x17\n\x0f\x66\x65tch_variables\x18\x03 \x03(\t\"\x1a\n\x18\x43ompleteUserTaskResponse\"e\n\x15\x41ssignUserTaskRequest\x12\x15\n\ruser_task_key\x18\x01 \x01(\x03\x12\x10\n\x08\x61ssignee\x18\x02 \x01(\t\x12#\n\x1b\x61llow_overriding_assignment\x18\x03 \x01(\x08\"\x18\n\x16\x41ssignUserTaskResponse\"0\n\x17UnassignUserTaskRequest\x12\x15\n\ruser_task_key\x18\x01 \x01(\x03\"\x1a\n\x18UnassignUserTaskResponse\"+\n\x12GetUserTaskRequest\x12\x15\n\ruser_task_key\x18\x01 \x01(\x03\"\xc7\x01\n\x13GetUserTaskResponse\x12\x15\n\ruser_task_key\x18\x01 \x01(\x03\x12\x10\n\x08\x61ssignee\x18\x02 \x01(\t\x12\x12\n\nelement_id\x18\x03 \x01(\t\x12\x1c\n\x14process_instance_key\x18\x04 \x01(\x03\x12\x10\n\x08\x66orm_key\x18\x05 \x01(\t\x12\x11\n\tvariables\x18\x06 \x01(\t\x12\x30\n\x05state\x18\x07 \x01(\x0e\x32!.user_task_protocol.UserTaskState*\x86\x01\n\rUserTaskState\x12\x1b\n\x17USER_TASK_STATE_UNKNOWN\x10\x00\x12\x1b\n\x17USER_TASK_STATE_CREATED\x10\x01\x12\x1d\n\x19USER_TASK_STATE_COMPLETED\x10\x02\x12\x1c\n\x18USER_TASK_STATE_CANCELED\x10\x03\x32\xb8\x03\n\x0fUserTaskGateway\x12m\n\x10\x43ompleteUserTask\x12+.user_task_protocol.CompleteUserTaskRequest\x1a,.user_task_protocol.CompleteUserTaskResponse\x12g\n\x0e\x41ssignUserTask\x12).user_task_protocol.AssignUserTaskRequest\x1a*.user_task_protocol.AssignUserTaskResponse\x12m\n\x10UnassignUserTask\x12+.user_task_protocol.UnassignUserTaskRequest\x1a,.user_task_protocol.UnassignUserTaskResponse\x12^\n\x0bGetUserTask\x12&.user_task_protocol.GetUserTaskRequest\x1a\'.user_task_protocol.GetUserTaskResponseB6\n#io.camunda.zeebe.user.task.protocolP\x01Z\r./;usertaskpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#io.camunda.zeebe.user.task.protocolP\001Z\r./;usertaskpb'
  _globals['_USERTASKSTATE']._serialized_start=616
  _globals['_USERTASKSTATE']._serialized_end=750
  _globals['_COMPLETEUSERTASKREQUEST']._serialized_start=39
  _globals['_COMPLETEUSERTASKREQUEST']._serialized_end=131
  _globals['_COMPLETEUSERTASKRESPONSE']._serialized_start=133
  _globals['_COMPLETEUSERTASKRESPONSE']._serialized_end=159
  _globals['_ASSIGNUSERTASKREQUEST']._serialized_start=161
  _globals['_ASSIGNUSERTASKREQUEST']._serialized_end=262
  _globals['_ASSIGNUSERTASKRESPONSE']._serialized_start=264
  _globals['_ASSIGNUSERTASKRESPONSE']._serialized_end=288
  _globals['_UNASSIGNUSERTASKREQUEST']._serialized_start=290
  _globals['_UNASSIGNUSERTASKREQUEST']._serialized_end=338
  _globals['_UNASSIGNUSERTASKRESPONSE']._serialized_start=340
  _globals['_UNASSIGNUSERTASKRESPONSE']._serialized_end=366
  _globals['_GETUSERTASKREQUEST']._serialized_start=368
  _globals['_GETUSERTASKREQUEST']._serialized_end=411
  _globals['_GETUSERTASKRESPONSE']._serialized_start=414
  _globals['_GETUSERTASKRESPONSE']._serialized_end=613
  _globals['_USERTASKGATEWAY']._serialized_start=753
  _globals['_USERTASKGATEWAY']._serialized_end=1193
# @@protoc_insertion_point(module_scope)
