# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_task_pb2 as user__task__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_task_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserTaskGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompleteUserTask = channel.unary_unary(
                '/user_task_protocol.UserTaskGateway/CompleteUserTask',
                request_serializer=user__task__pb2.CompleteUserTaskRequest.SerializeToString,
                response_deserializer=user__task__pb2.CompleteUserTaskResponse.FromString,
                _registered_method=True)
        self.AssignUserTask = channel.unary_unary(
                '/user_task_protocol.UserTaskGateway/AssignUserTask',
                request_serializer=user__task__pb2.AssignUserTaskRequest.SerializeToString,
                response_deserializer=user__task__pb2.AssignUserTaskResponse.FromString,
                _registered_method=True)
        self.UnassignUserTask = channel.unary_unary(
                '/user_task_protocol.UserTaskGateway/UnassignUserTask',
                request_serializer=user__task__pb2.UnassignUserTaskRequest.SerializeToString,
                response_deserializer=user__task__pb2.UnassignUserTaskResponse.FromString,
                _registered_method=True)
        self.GetUserTask = channel.unary_unary(
                '/user_task_protocol.UserTaskGateway/GetUserTask',
                request_serializer=user__task__pb2.GetUserTaskRequest.SerializeToString,
                response_deserializer=user__task__pb2.GetUserTaskResponse.FromString,
                _registered_method=True)


class UserTaskGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CompleteUserTask(self, request, context):
        """User Task operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignUserTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnassignUserTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserTaskGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompleteUserTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteUserTask,
                    request_deserializer=user__task__pb2.CompleteUserTaskRequest.FromString,
                    response_serializer=user__task__pb2.CompleteUserTaskResponse.SerializeToString,
            ),
            'AssignUserTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignUserTask,
                    request_deserializer=user__task__pb2.AssignUserTaskRequest.FromString,
                    response_serializer=user__task__pb2.AssignUserTaskResponse.SerializeToString,
            ),
            'UnassignUserTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UnassignUserTask,
                    request_deserializer=user__task__pb2.UnassignUserTaskRequest.FromString,
                    response_serializer=user__task__pb2.UnassignUserTaskResponse.SerializeToString,
            ),
            'GetUserTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserTask,
                    request_deserializer=user__task__pb2.GetUserTaskRequest.FromString,
                    response_serializer=user__task__pb2.GetUserTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user_task_protocol.UserTaskGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user_task_protocol.UserTaskGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserTaskGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CompleteUserTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_task_protocol.UserTaskGateway/CompleteUserTask',
            user__task__pb2.CompleteUserTaskRequest.SerializeToString,
            user__task__pb2.CompleteUserTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignUserTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_task_protocol.UserTaskGateway/AssignUserTask',
            user__task__pb2.AssignUserTaskRequest.SerializeToString,
            user__task__pb2.AssignUserTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnassignUserTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_task_protocol.UserTaskGateway/UnassignUserTask',
            user__task__pb2.UnassignUserTaskRequest.SerializeToString,
            user__task__pb2.UnassignUserTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_task_protocol.UserTaskGateway/GetUserTask',
            user__task__pb2.GetUserTaskRequest.SerializeToString,
            user__task__pb2.GetUserTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
